test_that("viewer fixtures cover arbitrary organs and preserve image/annotation identity", {
  d <- bs_viewer_example(); on.exit(unlink(d$directory, recursive = TRUE))
  expect_equal(length(unique(d$results$slides$organ)), 4L)
  expect_true(bs_validate(d$results))
  expect_true(all(file.exists(d$images$path)))
  m <- .bs_image_manifest(d$images, d$results$slides$physical_slide_id)
  expect_equal(m$scale_x, rep(1, 8))
  f <- .bs_annotations(m[1, ])
  expect_length(f, 12)
  expect_equal(length(f), d$results$slides$candidate_spots[1])
  expect_equal(f[[1]]$id, "candidate-1")
  expect_equal(f[[1]]$properties$classification$name, "Candidate")
  row <- m[1, ]; row$scale_x <- 2; row$offset_y <- 3
  z <- .bs_annotations(row)
  expect_equal(unlist(z[[1]]$geometry$coordinates), unlist(f[[1]]$geometry$coordinates) * c(2, 1) + c(0, 3))
  row$annotations <- ""
  expect_length(.bs_annotations(row), 0)
  info <- .bs_image_info(row, "", tempdir())
  expect_equal(info$type, "image")
  response <- .bs_image_response(info, list())
  expect_equal(response$status, 200L)
  expect_identical(response$content, readBin(row$path, "raw", file.info(row$path)$size))
  row$path <- tempfile(fileext = ".jpg"); writeBin(as.raw(1:3), row$path)
  on.exit(unlink(row$path), add = TRUE)
  expect_equal(.bs_image_info(row, "", tempdir())$mime, "image/jpeg")
})

test_that("image manifests resolve relative paths without trusting uploaded result paths", {
  root <- tempfile(); dir.create(root); on.exit(unlink(root, recursive = TRUE))
  image <- file.path(root, "preview.png"); writeBin(as.raw(1:3), image)
  d <- data.frame(image_id = "i", slide_id = "001", path = "preview.png")
  path <- file.path(root, "images.csv"); write.csv(d, path, row.names = FALSE)
  m <- .bs_image_manifest(path, "001")
  expect_equal(m$path, normalizePath(image))
  expect_equal(m$label, "i")
  expect_equal(nrow(.bs_image_manifest(NULL, "001")), 0)
  expect_error(.bs_image_manifest(data.frame(), "001"), "needs")
  d$path <- image
  expect_error(.bs_image_manifest(d, "other"), "must match")
  expect_error(.bs_image_manifest(rbind(d, d), "001"), "unique")
  d$image_id <- " "
  expect_error(.bs_image_manifest(d, "001"), "nonempty")
  d$image_id <- "i"; d$scale_x <- 0
  expect_error(.bs_image_manifest(d, "001"), "positive scales")
  d$scale_x <- 1; d$label <- NA_character_
  expect_error(.bs_image_manifest(d, "001"), "labels")
  d$label <- "preview"; d$path <- "absent.png"
  expect_error(.bs_image_manifest(d, "001"), "does not exist")
})

test_that("GeoJSON polygons and CSV points preserve measurements and reject bad geometry", {
  p <- tempfile(fileext = ".geojson"); on.exit(unlink(p))
  row <- data.frame(annotations = p, scale_x = 1, scale_y = 1, offset_x = 0, offset_y = 0)
  f <- list(type = "Feature", id = "roi-1", properties = list(measurements = list(area = 12)),
            geometry = list(type = "Polygon", coordinates = list(list(c(0, 0), c(10, 0), c(10, 10), c(0, 0)))))
  write <- function(x) jsonlite::write_json(x, p, auto_unbox = TRUE)
  write(f)
  expect_equal(.bs_annotations(row)[[1]]$properties$measurements$area, 12)
  f$id <- NULL; f$properties <- NULL; write(f)
  expect_equal(.bs_annotations(row)[[1]]$id, "1")
  f$geometry$type <- "GeometryCollection"; write(f)
  expect_error(.bs_annotations(row), "Unsupported")
  f$geometry <- list(type = "Point", coordinates = c(1, Inf)); write(f)
  expect_error(.bs_annotations(row), "coordinates")
  f$geometry$coordinates <- c(1, 2); f$id <- "same"
  write(list(type = "FeatureCollection", features = list(f, f)))
  expect_error(.bs_annotations(row), "unique")
  write(list(type = "unknown")); expect_error(.bs_annotations(row), "GeoJSON")
  p2 <- tempfile(fileext = ".csv"); on.exit(unlink(p2), add = TRUE)
  row$annotations <- p2
  writeLines(c('annotation_id,x,y,intensity', '001,2,3,42'), p2)
  z <- .bs_annotations(row)
  expect_identical(z[[1]]$id, "001")
  expect_identical(z[[1]]$properties$intensity, "42")
  writeLines(c('x,wrong', '2,3'), p2)
  expect_error(.bs_annotations(row), "x and y")
})

test_that("native tile responses validate coordinates, cache and contain reader failures", {
  cache <- tempfile(); dir.create(cache); on.exit(unlink(cache, recursive = TRUE))
  source <- file.path(cache, "slide.svs"); writeBin(as.raw(1), source)
  calls <- 0L
  local_mocked_bindings(.bs_slide_python = function(python, args) {
    calls <<- calls + 1L
    if (args[1] == "info") return('{"width":1024,"height":512,"max_level":10,"vendor":"fixture"}')
    writeBin(as.raw(c(137, 80, 78, 71)), tail(args, 1))
    ""
  })
  data <- .bs_image_info(data.frame(path = source), "python", cache)
  expect_equal(data$width, 1024)
  expect_equal(.bs_image_response(data, list(QUERY_STRING = "level=-1&x=0&y=0"))$status, 400L)
  expect_equal(.bs_image_response(data, list(QUERY_STRING = "level=11&x=0&y=0"))$status, 400L)
  req <- list(QUERY_STRING = "level=10&x=0&y=0")
  expect_equal(.bs_image_response(data, req)$status, 200L)
  expect_equal(.bs_image_response(data, req)$status, 200L)
  expect_equal(calls, 2L)
  unlink(source)
  data$type <- "image"
  expect_warning(expect_equal(.bs_image_response(data, list())$status, 422L))
})

test_that("viewer session links selection and saved annotation refresh", {
  skip_if_not_installed("shiny")
  d <- bs_viewer_example(); on.exit(unlink(d$directory, recursive = TRUE))
  m <- .bs_image_manifest(d$images, d$results$slides$physical_slide_id)
  suppressWarnings(shiny::testServer(.bs_app_server(.bs_app_results(d$results), m), {
    session$setInputs(organ = "", qc = "", search = "", selected_slide = "DEMO-001", selected_image = "image-1")
    expect_equal(viewer$payload()$image_id, "image-1")
    expect_length(viewer$payload()$features, 12)
    session$setInputs(viewer_annotation = list(image_id = "image-1", id = "candidate-1"),
                      selected_annotation = "candidate-1")
    expect_match(output$annotation_measurements, "Illustrative diameter")
    expect_match(output$selected_measurements, "DEMO-001")
    session$setInputs(next_slide = 1, selected_slide = "DEMO-003", selected_image = "image-3")
    expect_equal(viewer$payload()$image_id, "image-3")
    session$setInputs(previous_slide = 1, show_annotations = FALSE)
    session$setInputs(selected_slide = "missing", selected_image = "")
    expect_true(viewer$payload()$empty)
    expect_match(output$viewer_status, "No image linked")
  }))
})

test_that("custom grouping and saved-result refresh preserve usable prior data", {
  skip_if_not_installed("shiny")
  x <- bs_example(); x$slides$site <- rep(c("Brain", "Skin", "Heart", "Tumor"), 2)
  path <- tempfile(fileext = ".json"); on.exit(unlink(path))
  save <- function(x) jsonlite::write_json(unclass(x), path, auto_unbox = TRUE, dataframe = "rows", na = "null")
  save(x)
  expect_s3_class(bs_app(path, launch = FALSE, group_by = "site", group_label = "Sample", title = "Collection"), "shiny.appobj")
  expect_error(bs_app(x, launch = FALSE, group_by = "absent"), "group_by")
  shiny::testServer(.bs_app_server(.bs_app_results(x), result_path = path, group_by = "site"), {
    session$setInputs(organ = "Brain", qc = "", search = "", refresh_slide = 0)
    expect_equal(nrow(filtered()), 2)
    y <- x; y$slides$red_area_mm2[1] <- .7; save(y)
    session$setInputs(refresh_slide = 1)
    expect_equal(current()$slides$red_area_mm2[1], .7)
    writeLines("broken", path)
    session$setInputs(refresh_slide = 2)
    expect_match(output$viewer_status, "previous measurements retained")
    expect_equal(current()$slides$red_area_mm2[1], .7)
    save(x); session$setInputs(live_refresh = TRUE)
    session$elapse(2100)
    expect_equal(current()$slides$red_area_mm2[1], 0)
    session$setInputs(live_refresh = FALSE)
    upload <- tempfile(fileext = ".csv")
    write.csv(x$slides, upload, row.names = FALSE)
    session$setInputs(upload = data.frame(name = "valid.csv", datapath = upload))
    expect_match(output$status, "Imported")
    expect_null(watched_path())
    write.csv(bs_example()$slides, upload, row.names = FALSE)
    session$setInputs(upload = data.frame(name = "missing-group.csv", datapath = upload))
    expect_match(output$status, "Missing grouping column")
    session$setInputs(demo = 1)
    expect_true("site" %in% names(current()$slides))
    unlink(upload)
  })
})

test_that("native subprocess errors and argument transport have bounded behavior", {
  skip_if_not_installed("processx")
  expect_error(.bs_slide_python("", c("info", "missing.svs")), "slide_python")
  calls <- list()
  local_mocked_bindings(run = function(command, args, ...) {
    calls[[length(calls) + 1L]] <<- list(command = command, args = args, settings = list(...))
    if (command == "bad") return(list(status = 1L, stderr = "reader error"))
    list(status = 0L, stdout = '{"width":1}', stderr = "")
  }, .package = "processx")
  expect_match(.bs_slide_python("python", c("info", "a path.svs")), "width")
  expect_equal(tail(calls[[1]]$args, 2), c("info", "a path.svs"))
  expect_equal(calls[[1]]$settings$timeout, 30)
  expect_true(calls[[1]]$settings$cleanup_tree)
  expect_error(.bs_slide_python("bad", c("info", "x")), "reader error")
})

test_that("upload request limits are scoped to the running application", {
  skip_if_not_installed("shiny")
  old <- getOption("shiny.maxRequestSize"); on.exit(options(shiny.maxRequestSize = old))
  cleanup <- NULL
  local_mocked_bindings(onStop = function(fun, ...) { cleanup <<- fun }, .package = "shiny")
  options(shiny.maxRequestSize = 1024)
  .bs_app_start()
  expect_equal(getOption("shiny.maxRequestSize"), 20 * 1024^2)
  cleanup()
  expect_equal(getOption("shiny.maxRequestSize"), 1024)
  options(shiny.maxRequestSize = 30 * 1024^2)
  .bs_app_start()
  expect_equal(getOption("shiny.maxRequestSize"), 30 * 1024^2)
  options(shiny.maxRequestSize = 40 * 1024^2)
  cleanup()
  expect_equal(getOption("shiny.maxRequestSize"), 40 * 1024^2)
})

test_that("annotation properties become readable values without discarding metadata", {
  p <- list(classification = list(name = "Tumor"),
    measurements = list(list(name = "Area", value = 12), list(name = "Score", value = NA_real_)),
    notes = "<script>", extra = list(a = 1), missing = NULL)
  table <- .bs_annotation_values(p)
  expect_equal(table$Value[table$Measurement == "Class"], "Tumor")
  expect_equal(table$Value[table$Measurement == "Area"], "12")
  expect_equal(table$Value[table$Measurement == "Score"], "Missing")
  expect_equal(table$Value[table$Measurement == "notes"], "<script>")
  expect_equal(.bs_annotation_values(list())$Value, "None supplied")
  expect_equal(.bs_annotation_values(list(measurements = list(area = 42)))$Value, "42")
  expect_equal(.bs_annotation_values(list(measurements = list(2)))$Value, "2")
})
