test_that("project creation is portable, explicit and nondestructive", {
  skip_if_not_installed("jsonlite")
  p <- tempfile(); on.exit(unlink(p, recursive = TRUE))
  expect_error(bs_project(p), "No bloodspottr")
  z <- bs_project(p, create = TRUE)
  expect_s3_class(z, "bs_project")
  expect_true(bs_validate(z))
  expect_equal(bs_status(z)$registered_results, 0)
  expect_true(is.na(bs_status(z)$running_jobs))
  expect_identical(bs_project(p)$manifest, z$manifest)
  expect_error(bs_project(p, create = TRUE), "empty directory")
  expect_error(bs_project(p, create = NA), "TRUE or FALSE")
  expect_error(bs_project(NA_character_), "nonempty")
  jsonlite::write_json(list(schema_version = "unsupported"), file.path(p, "bloodspottr-project.json"))
  expect_error(bs_project(p), "unsupported")
  f <- tempfile(); writeLines("keep", f); on.exit(unlink(f), add = TRUE)
  expect_error(bs_project(f, TRUE), "not a directory")
  expect_equal(readLines(f), "keep")
})
